# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_peekSharedMemory <- function(x) {
    .Call(`_sharedObject_C_peekSharedMemory`, x)
}

C_testFunc <- function(a) {
    .Call(`_sharedObject_C_testFunc`, a)
}

C_findAvailableKey <- function(did) {
    .Call(`_sharedObject_C_findAvailableKey`, did)
}

C_createSharedMemory <- function(R_x, R_dataInfo) {
    invisible(.Call(`_sharedObject_C_createSharedMemory`, R_x, R_dataInfo))
}

C_readSharedMemory <- function(dataID) {
    .Call(`_sharedObject_C_readSharedMemory`, dataID)
}

C_createAltrep <- function(SM_obj) {
    .Call(`_sharedObject_C_createAltrep`, SM_obj)
}

C_clearObj <- function(did) {
    invisible(.Call(`_sharedObject_C_clearObj`, did))
}

C_getDataIDList <- function() {
    .Call(`_sharedObject_C_getDataIDList`)
}

C_attachAttr <- function(R_source, R_tag, R_attr) {
    .Call(`_sharedObject_C_attachAttr`, R_source, R_tag, R_attr)
}

C_ALTREP <- function(x) {
    .Call(`_sharedObject_C_ALTREP`, x)
}

C_getDataID <- function(did) {
    .Call(`_sharedObject_C_getDataID`, did)
}

C_getProcessID <- function(did) {
    .Call(`_sharedObject_C_getProcessID`, did)
}

C_getTypeID <- function(did) {
    .Call(`_sharedObject_C_getTypeID`, did)
}

C_getLength <- function(did) {
    .Call(`_sharedObject_C_getLength`, did)
}

C_getTotalSize <- function(did) {
    .Call(`_sharedObject_C_getTotalSize`, did)
}

C_getCopyOnWrite <- function(did) {
    .Call(`_sharedObject_C_getCopyOnWrite`, did)
}

C_getSharedSubset <- function(did) {
    .Call(`_sharedObject_C_getSharedSubset`, did)
}

C_getSharedDuplicate <- function(did) {
    .Call(`_sharedObject_C_getSharedDuplicate`, did)
}

C_setCopyOnWrite <- function(did, value) {
    invisible(.Call(`_sharedObject_C_setCopyOnWrite`, did, value))
}

C_setSharedSub <- function(did, value) {
    invisible(.Call(`_sharedObject_C_setSharedSub`, did, value))
}

C_setSharedDuplicate <- function(did, value) {
    invisible(.Call(`_sharedObject_C_setSharedDuplicate`, did, value))
}

