# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_getSharedProperty <- function(x) {
    .Call(`_SharedObject_C_getSharedProperty`, x)
}

C_testFunc <- function(a) {
    .Call(`_SharedObject_C_testFunc`, a)
}

C_findAvailableKey <- function(dataID) {
    .Call(`_SharedObject_C_findAvailableKey`, dataID)
}

C_createSharedMemory <- function(R_x, R_dataInfo) {
    invisible(.Call(`_SharedObject_C_createSharedMemory`, R_x, R_dataInfo))
}

C_readSharedMemory <- function(dataID) {
    .Call(`_SharedObject_C_readSharedMemory`, dataID)
}

C_createAltrep <- function(SM_obj) {
    .Call(`_SharedObject_C_createAltrep`, SM_obj)
}

C_clearObj <- function(dataID) {
    invisible(.Call(`_SharedObject_C_clearObj`, dataID))
}

C_getDataIDList <- function() {
    .Call(`_SharedObject_C_getDataIDList`)
}

C_getDataInfo <- function(dataID) {
    .Call(`_SharedObject_C_getDataInfo`, dataID)
}

C_attachAttr <- function(R_source, R_tag, R_attr) {
    .Call(`_SharedObject_C_attachAttr`, R_source, R_tag, R_attr)
}

C_ALTREP <- function(x) {
    .Call(`_SharedObject_C_ALTREP`, x)
}

C_getDataID <- function(did) {
    .Call(`_SharedObject_C_getDataID`, did)
}

C_getProcessID <- function(did) {
    .Call(`_SharedObject_C_getProcessID`, did)
}

C_getTypeID <- function(did) {
    .Call(`_SharedObject_C_getTypeID`, did)
}

C_getLength <- function(did) {
    .Call(`_SharedObject_C_getLength`, did)
}

C_getTotalSize <- function(did) {
    .Call(`_SharedObject_C_getTotalSize`, did)
}

C_getCopyOnWrite <- function(did) {
    .Call(`_SharedObject_C_getCopyOnWrite`, did)
}

C_getSharedSubset <- function(did) {
    .Call(`_SharedObject_C_getSharedSubset`, did)
}

C_getSharedCopy <- function(did) {
    .Call(`_SharedObject_C_getSharedCopy`, did)
}

C_setCopyOnWrite <- function(did, value) {
    invisible(.Call(`_SharedObject_C_setCopyOnWrite`, did, value))
}

C_setSharedSubset <- function(did, value) {
    invisible(.Call(`_SharedObject_C_setSharedSubset`, did, value))
}

C_setSharedCopy <- function(did, value) {
    invisible(.Call(`_SharedObject_C_setSharedCopy`, did, value))
}

